// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmZQTLpm20nsAVHFJmCwTegRjVNwAyLas',
    appId: '1:579622930240:android:98235adf8e1e9ae346dca5',
    messagingSenderId: '579622930240',
    projectId: 'projeto-monitoramento-39de2',
    databaseURL: 'https://projeto-monitoramento-39de2-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-monitoramento-39de2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_RqiRKZtZbiUsjIWu5fFk7rHg74iP-ZI',
    appId: '1:579622930240:ios:690dc6d032c82bad46dca5',
    messagingSenderId: '579622930240',
    projectId: 'projeto-monitoramento-39de2',
    databaseURL: 'https://projeto-monitoramento-39de2-default-rtdb.firebaseio.com',
    storageBucket: 'projeto-monitoramento-39de2.appspot.com',
    iosClientId: '579622930240-m583suejshs9g2ectapdq67u5bp5cuj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.trabalhoiot2',
  );
}
